version: '3.8'

services:
  app:
    container_name: fishing-api
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./public:/app/public
      - go-cache:/root/.cache/go-build
      - go-mod:/go/pkg/mod
    networks:
      -  common_network

  mysql:
    container_name: fishing-db
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    tmpfs:
      - /var/log/mysql
    environment:
      - DB_USER=user
      - DB_PASS=passpw
      - DB_DATABASE=story_fishing_db
      - DB_ROOT_PASS=rootpw
    env_file:
      - .env
    ports:
      - "13306:3306"
    networks:
      - common_network

volumes:
  go-cache:
  go-mod:

networks:
  common_network:
